services:
  postgres:
    image: postgres:16-alpine
    container_name: gophermart_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: gophermart
      POSTGRES_PASSWORD: gophermart
      POSTGRES_DB: gophermart
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U gophermart -d gophermart"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
