// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package api

import (
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"time"

	"github.com/labstack/echo/v4"
	strictecho "github.com/oapi-codegen/runtime/strictmiddleware/echo"
)

const (
	CookieAuthScopes = "cookieAuth.Scopes"
)

// Defines values for OrderInfoStatus.
const (
	INVALID    OrderInfoStatus = "INVALID"
	NEW        OrderInfoStatus = "NEW"
	PROCESSED  OrderInfoStatus = "PROCESSED"
	PROCESSING OrderInfoStatus = "PROCESSING"
)

// Valid indicates whether the value is a known member of the OrderInfoStatus enum.
func (e OrderInfoStatus) Valid() bool {
	switch e {
	case INVALID:
		return true
	case NEW:
		return true
	case PROCESSED:
		return true
	case PROCESSING:
		return true
	default:
		return false
	}
}

// Balance defines model for Balance.
type Balance struct {
	// Current Current points balance
	Current float32 `json:"current"`

	// Withdrawn Total points withdrawn over history
	Withdrawn float32 `json:"withdrawn"`
}

// Credentials defines model for Credentials.
type Credentials struct {
	Login    string `json:"login"`
	Password string `json:"password"`
}

// Error defines model for Error.
type Error struct {
	// Message Error description
	Message *string `json:"message,omitempty"`
}

// OrderInfo defines model for OrderInfo.
type OrderInfo struct {
	// Accrual Accrued points (present only for PROCESSED status)
	Accrual *float32 `json:"accrual,omitempty"`

	// Number Order number
	Number string `json:"number"`

	// Status Processing status of the order
	Status OrderInfoStatus `json:"status"`

	// UploadedAt Upload timestamp in RFC3339 format
	UploadedAt time.Time `json:"uploaded_at"`
}

// OrderInfoStatus Processing status of the order
type OrderInfoStatus string

// WithdrawRequest defines model for WithdrawRequest.
type WithdrawRequest struct {
	// Order Order number to pay with points
	Order string `json:"order"`

	// Sum Amount of points to withdraw
	Sum float32 `json:"sum"`
}

// Withdrawal defines model for Withdrawal.
type Withdrawal struct {
	// Order Order number for which points were withdrawn
	Order string `json:"order"`

	// ProcessedAt Withdrawal timestamp in RFC3339 format
	ProcessedAt time.Time `json:"processed_at"`

	// Sum Amount withdrawn
	Sum float32 `json:"sum"`
}

// UploadOrderTextBody defines parameters for UploadOrder.
type UploadOrderTextBody = string

// WithdrawPointsJSONRequestBody defines body for WithdrawPoints for application/json ContentType.
type WithdrawPointsJSONRequestBody = WithdrawRequest

// LoginUserJSONRequestBody defines body for LoginUser for application/json ContentType.
type LoginUserJSONRequestBody = Credentials

// UploadOrderTextRequestBody defines body for UploadOrder for text/plain ContentType.
type UploadOrderTextRequestBody = UploadOrderTextBody

// RegisterUserJSONRequestBody defines body for RegisterUser for application/json ContentType.
type RegisterUserJSONRequestBody = Credentials

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Get current loyalty points balance and total withdrawn
	// (GET /api/user/balance)
	GetBalance(ctx echo.Context) error
	// Withdraw points to pay for a new order
	// (POST /api/user/balance/withdraw)
	WithdrawPoints(ctx echo.Context) error
	// Authenticate user
	// (POST /api/user/login)
	LoginUser(ctx echo.Context) error
	// Get list of uploaded orders with statuses and accruals
	// (GET /api/user/orders)
	GetOrders(ctx echo.Context) error
	// Upload an order number for processing
	// (POST /api/user/orders)
	UploadOrder(ctx echo.Context) error
	// Register a new user
	// (POST /api/user/register)
	RegisterUser(ctx echo.Context) error
	// Get withdrawal history
	// (GET /api/user/withdrawals)
	GetWithdrawals(ctx echo.Context) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// GetBalance converts echo context to params.
func (w *ServerInterfaceWrapper) GetBalance(ctx echo.Context) error {
	var err error

	ctx.Set(CookieAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetBalance(ctx)
	return err
}

// WithdrawPoints converts echo context to params.
func (w *ServerInterfaceWrapper) WithdrawPoints(ctx echo.Context) error {
	var err error

	ctx.Set(CookieAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.WithdrawPoints(ctx)
	return err
}

// LoginUser converts echo context to params.
func (w *ServerInterfaceWrapper) LoginUser(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.LoginUser(ctx)
	return err
}

// GetOrders converts echo context to params.
func (w *ServerInterfaceWrapper) GetOrders(ctx echo.Context) error {
	var err error

	ctx.Set(CookieAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetOrders(ctx)
	return err
}

// UploadOrder converts echo context to params.
func (w *ServerInterfaceWrapper) UploadOrder(ctx echo.Context) error {
	var err error

	ctx.Set(CookieAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.UploadOrder(ctx)
	return err
}

// RegisterUser converts echo context to params.
func (w *ServerInterfaceWrapper) RegisterUser(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.RegisterUser(ctx)
	return err
}

// GetWithdrawals converts echo context to params.
func (w *ServerInterfaceWrapper) GetWithdrawals(ctx echo.Context) error {
	var err error

	ctx.Set(CookieAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetWithdrawals(ctx)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.GET(baseURL+"/api/user/balance", wrapper.GetBalance)
	router.POST(baseURL+"/api/user/balance/withdraw", wrapper.WithdrawPoints)
	router.POST(baseURL+"/api/user/login", wrapper.LoginUser)
	router.GET(baseURL+"/api/user/orders", wrapper.GetOrders)
	router.POST(baseURL+"/api/user/orders", wrapper.UploadOrder)
	router.POST(baseURL+"/api/user/register", wrapper.RegisterUser)
	router.GET(baseURL+"/api/user/withdrawals", wrapper.GetWithdrawals)

}

type GetBalanceRequestObject struct {
}

type GetBalanceResponseObject interface {
	VisitGetBalanceResponse(w http.ResponseWriter) error
}

type GetBalance200JSONResponse Balance

func (response GetBalance200JSONResponse) VisitGetBalanceResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetBalance401JSONResponse Error

func (response GetBalance401JSONResponse) VisitGetBalanceResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type GetBalance500JSONResponse Error

func (response GetBalance500JSONResponse) VisitGetBalanceResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type WithdrawPointsRequestObject struct {
	Body *WithdrawPointsJSONRequestBody
}

type WithdrawPointsResponseObject interface {
	VisitWithdrawPointsResponse(w http.ResponseWriter) error
}

type WithdrawPoints200Response struct {
}

func (response WithdrawPoints200Response) VisitWithdrawPointsResponse(w http.ResponseWriter) error {
	w.WriteHeader(200)
	return nil
}

type WithdrawPoints401JSONResponse Error

func (response WithdrawPoints401JSONResponse) VisitWithdrawPointsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type WithdrawPoints402JSONResponse Error

func (response WithdrawPoints402JSONResponse) VisitWithdrawPointsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(402)

	return json.NewEncoder(w).Encode(response)
}

type WithdrawPoints422JSONResponse Error

func (response WithdrawPoints422JSONResponse) VisitWithdrawPointsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(422)

	return json.NewEncoder(w).Encode(response)
}

type WithdrawPoints500JSONResponse Error

func (response WithdrawPoints500JSONResponse) VisitWithdrawPointsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type LoginUserRequestObject struct {
	Body *LoginUserJSONRequestBody
}

type LoginUserResponseObject interface {
	VisitLoginUserResponse(w http.ResponseWriter) error
}

type LoginUser200ResponseHeaders struct {
	SetCookie string
}

type LoginUser200Response struct {
	Headers LoginUser200ResponseHeaders
}

func (response LoginUser200Response) VisitLoginUserResponse(w http.ResponseWriter) error {
	w.Header().Set("Set-Cookie", fmt.Sprint(response.Headers.SetCookie))
	w.WriteHeader(200)
	return nil
}

type LoginUser400JSONResponse Error

func (response LoginUser400JSONResponse) VisitLoginUserResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type LoginUser401JSONResponse Error

func (response LoginUser401JSONResponse) VisitLoginUserResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type LoginUser500JSONResponse Error

func (response LoginUser500JSONResponse) VisitLoginUserResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetOrdersRequestObject struct {
}

type GetOrdersResponseObject interface {
	VisitGetOrdersResponse(w http.ResponseWriter) error
}

type GetOrders200JSONResponse []OrderInfo

func (response GetOrders200JSONResponse) VisitGetOrdersResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetOrders204Response struct {
}

func (response GetOrders204Response) VisitGetOrdersResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type GetOrders401JSONResponse Error

func (response GetOrders401JSONResponse) VisitGetOrdersResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type GetOrders500JSONResponse Error

func (response GetOrders500JSONResponse) VisitGetOrdersResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type UploadOrderRequestObject struct {
	Body *UploadOrderTextRequestBody
}

type UploadOrderResponseObject interface {
	VisitUploadOrderResponse(w http.ResponseWriter) error
}

type UploadOrder200Response struct {
}

func (response UploadOrder200Response) VisitUploadOrderResponse(w http.ResponseWriter) error {
	w.WriteHeader(200)
	return nil
}

type UploadOrder202Response struct {
}

func (response UploadOrder202Response) VisitUploadOrderResponse(w http.ResponseWriter) error {
	w.WriteHeader(202)
	return nil
}

type UploadOrder400JSONResponse Error

func (response UploadOrder400JSONResponse) VisitUploadOrderResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type UploadOrder401JSONResponse Error

func (response UploadOrder401JSONResponse) VisitUploadOrderResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type UploadOrder409JSONResponse Error

func (response UploadOrder409JSONResponse) VisitUploadOrderResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)

	return json.NewEncoder(w).Encode(response)
}

type UploadOrder422JSONResponse Error

func (response UploadOrder422JSONResponse) VisitUploadOrderResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(422)

	return json.NewEncoder(w).Encode(response)
}

type UploadOrder500JSONResponse Error

func (response UploadOrder500JSONResponse) VisitUploadOrderResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type RegisterUserRequestObject struct {
	Body *RegisterUserJSONRequestBody
}

type RegisterUserResponseObject interface {
	VisitRegisterUserResponse(w http.ResponseWriter) error
}

type RegisterUser200ResponseHeaders struct {
	SetCookie string
}

type RegisterUser200Response struct {
	Headers RegisterUser200ResponseHeaders
}

func (response RegisterUser200Response) VisitRegisterUserResponse(w http.ResponseWriter) error {
	w.Header().Set("Set-Cookie", fmt.Sprint(response.Headers.SetCookie))
	w.WriteHeader(200)
	return nil
}

type RegisterUser400JSONResponse Error

func (response RegisterUser400JSONResponse) VisitRegisterUserResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type RegisterUser409JSONResponse Error

func (response RegisterUser409JSONResponse) VisitRegisterUserResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)

	return json.NewEncoder(w).Encode(response)
}

type RegisterUser500JSONResponse Error

func (response RegisterUser500JSONResponse) VisitRegisterUserResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetWithdrawalsRequestObject struct {
}

type GetWithdrawalsResponseObject interface {
	VisitGetWithdrawalsResponse(w http.ResponseWriter) error
}

type GetWithdrawals200JSONResponse []Withdrawal

func (response GetWithdrawals200JSONResponse) VisitGetWithdrawalsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetWithdrawals204Response struct {
}

func (response GetWithdrawals204Response) VisitGetWithdrawalsResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type GetWithdrawals401JSONResponse Error

func (response GetWithdrawals401JSONResponse) VisitGetWithdrawalsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type GetWithdrawals500JSONResponse Error

func (response GetWithdrawals500JSONResponse) VisitGetWithdrawalsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Get current loyalty points balance and total withdrawn
	// (GET /api/user/balance)
	GetBalance(ctx context.Context, request GetBalanceRequestObject) (GetBalanceResponseObject, error)
	// Withdraw points to pay for a new order
	// (POST /api/user/balance/withdraw)
	WithdrawPoints(ctx context.Context, request WithdrawPointsRequestObject) (WithdrawPointsResponseObject, error)
	// Authenticate user
	// (POST /api/user/login)
	LoginUser(ctx context.Context, request LoginUserRequestObject) (LoginUserResponseObject, error)
	// Get list of uploaded orders with statuses and accruals
	// (GET /api/user/orders)
	GetOrders(ctx context.Context, request GetOrdersRequestObject) (GetOrdersResponseObject, error)
	// Upload an order number for processing
	// (POST /api/user/orders)
	UploadOrder(ctx context.Context, request UploadOrderRequestObject) (UploadOrderResponseObject, error)
	// Register a new user
	// (POST /api/user/register)
	RegisterUser(ctx context.Context, request RegisterUserRequestObject) (RegisterUserResponseObject, error)
	// Get withdrawal history
	// (GET /api/user/withdrawals)
	GetWithdrawals(ctx context.Context, request GetWithdrawalsRequestObject) (GetWithdrawalsResponseObject, error)
}

type StrictHandlerFunc = strictecho.StrictEchoHandlerFunc
type StrictMiddlewareFunc = strictecho.StrictEchoMiddlewareFunc

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
}

// GetBalance operation middleware
func (sh *strictHandler) GetBalance(ctx echo.Context) error {
	var request GetBalanceRequestObject

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetBalance(ctx.Request().Context(), request.(GetBalanceRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetBalance")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetBalanceResponseObject); ok {
		return validResponse.VisitGetBalanceResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// WithdrawPoints operation middleware
func (sh *strictHandler) WithdrawPoints(ctx echo.Context) error {
	var request WithdrawPointsRequestObject

	var body WithdrawPointsJSONRequestBody
	if err := ctx.Bind(&body); err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.WithdrawPoints(ctx.Request().Context(), request.(WithdrawPointsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "WithdrawPoints")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(WithdrawPointsResponseObject); ok {
		return validResponse.VisitWithdrawPointsResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// LoginUser operation middleware
func (sh *strictHandler) LoginUser(ctx echo.Context) error {
	var request LoginUserRequestObject

	var body LoginUserJSONRequestBody
	if err := ctx.Bind(&body); err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.LoginUser(ctx.Request().Context(), request.(LoginUserRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "LoginUser")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(LoginUserResponseObject); ok {
		return validResponse.VisitLoginUserResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetOrders operation middleware
func (sh *strictHandler) GetOrders(ctx echo.Context) error {
	var request GetOrdersRequestObject

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetOrders(ctx.Request().Context(), request.(GetOrdersRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetOrders")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetOrdersResponseObject); ok {
		return validResponse.VisitGetOrdersResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// UploadOrder operation middleware
func (sh *strictHandler) UploadOrder(ctx echo.Context) error {
	var request UploadOrderRequestObject

	data, err := io.ReadAll(ctx.Request().Body)
	if err != nil {
		return err
	}
	body := UploadOrderTextRequestBody(data)
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.UploadOrder(ctx.Request().Context(), request.(UploadOrderRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UploadOrder")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(UploadOrderResponseObject); ok {
		return validResponse.VisitUploadOrderResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// RegisterUser operation middleware
func (sh *strictHandler) RegisterUser(ctx echo.Context) error {
	var request RegisterUserRequestObject

	var body RegisterUserJSONRequestBody
	if err := ctx.Bind(&body); err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.RegisterUser(ctx.Request().Context(), request.(RegisterUserRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "RegisterUser")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(RegisterUserResponseObject); ok {
		return validResponse.VisitRegisterUserResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetWithdrawals operation middleware
func (sh *strictHandler) GetWithdrawals(ctx echo.Context) error {
	var request GetWithdrawalsRequestObject

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetWithdrawals(ctx.Request().Context(), request.(GetWithdrawalsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetWithdrawals")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetWithdrawalsResponseObject); ok {
		return validResponse.VisitGetWithdrawalsResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}
